//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CardRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CardRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.CardRes", typeof(CardRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to result.
        /// </summary>
        public static string bilingStatus {
            get {
                return ResourceManager.GetString("bilingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart.
        /// </summary>
        public static string Cart {
            get {
                return ResourceManager.GetString("Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Info.
        /// </summary>
        public static string CheckInfo {
            get {
                return ResourceManager.GetString("CheckInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout.
        /// </summary>
        public static string Checkout {
            get {
                return ResourceManager.GetString("Checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quantity.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Partners.
        /// </summary>
        public static string DeliveryPartners {
            get {
                return ResourceManager.GetString("DeliveryPartners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string firstname {
            get {
                return ResourceManager.GetString("firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Service as beautiful as the art they sell...Saatchi facilitated the deal and worked extremely hard to make sure I received a deal I was happy with and could afford. They&apos;ve found a life long customer in me!&quot;.
        /// </summary>
        public static string getinfoRghtBar {
            get {
                return ResourceManager.GetString("getinfoRghtBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string lastname {
            get {
                return ResourceManager.GetString("lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to order number.
        /// </summary>
        public static string orderNumber {
            get {
                return ResourceManager.GetString("orderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to orders.
        /// </summary>
        public static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Work.
        /// </summary>
        public static string OriginalWork {
            get {
                return ResourceManager.GetString("OriginalWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pay.
        /// </summary>
        public static string pay {
            get {
                return ResourceManager.GetString("pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Methods.
        /// </summary>
        public static string PaymentMethods {
            get {
                return ResourceManager.GetString("PaymentMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to payment result.
        /// </summary>
        public static string PaymentResult {
            get {
                return ResourceManager.GetString("PaymentResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7 days money back guarantee.
        /// </summary>
        public static string r1 {
            get {
                return ResourceManager.GetString("r1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast and safely delivery to your door, worldwide.
        /// </summary>
        public static string r2 {
            get {
                return ResourceManager.GetString("r2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taking your order 24/7.
        /// </summary>
        public static string r3 {
            get {
                return ResourceManager.GetString("r3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure payment.
        /// </summary>
        public static string r4 {
            get {
                return ResourceManager.GetString("r4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnSuccessful.
        /// </summary>
        public static string ResultFalse {
            get {
                return ResourceManager.GetString("ResultFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful.
        /// </summary>
        public static string ResultTrue {
            get {
                return ResourceManager.GetString("ResultTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        public static string Review {
            get {
                return ResourceManager.GetString("Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure Transaction.
        /// </summary>
        public static string SecureTransaction {
            get {
                return ResourceManager.GetString("SecureTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtotal.
        /// </summary>
        public static string Subtotal {
            get {
                return ResourceManager.GetString("Subtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total price.
        /// </summary>
        public static string TotalPrice {
            get {
                return ResourceManager.GetString("TotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to transaction number.
        /// </summary>
        public static string transactionNumber {
            get {
                return ResourceManager.GetString("transactionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter only digits..
        /// </summary>
        public static string ValidateDigits {
            get {
                return ResourceManager.GetString("ValidateDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a value less than or equal to.
        /// </summary>
        public static string ValidateMax {
            get {
                return ResourceManager.GetString("ValidateMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter no more than.
        /// </summary>
        public static string ValidateMaxlength {
            get {
                return ResourceManager.GetString("ValidateMaxlength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a value greater than or equal to.
        /// </summary>
        public static string ValidateMin {
            get {
                return ResourceManager.GetString("ValidateMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter at least.
        /// </summary>
        public static string ValidateMinlength {
            get {
                return ResourceManager.GetString("ValidateMinlength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid number..
        /// </summary>
        public static string ValidateNumber {
            get {
                return ResourceManager.GetString("ValidateNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a value between.
        /// </summary>
        public static string ValidateRange {
            get {
                return ResourceManager.GetString("ValidateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a value between.
        /// </summary>
        public static string ValidateRangelength {
            get {
                return ResourceManager.GetString("ValidateRangelength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required..
        /// </summary>
        public static string ValidateRequired {
            get {
                return ResourceManager.GetString("ValidateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip / Postal Code.
        /// </summary>
        public static string zipcode {
            get {
                return ResourceManager.GetString("zipcode", resourceCulture);
            }
        }
    }
}
