//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FooterRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FooterRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.FooterRes", typeof(FooterRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string About_Us {
            get {
                return ResourceManager.GetString("About_Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affiliate Program.
        /// </summary>
        public static string Affiliate_Program {
            get {
                return ResourceManager.GetString("Affiliate_Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agency Handbook.
        /// </summary>
        public static string Agency_Handbook {
            get {
                return ResourceManager.GetString("Agency_Handbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Art Advisory Services.
        /// </summary>
        public static string Art_Advisory_Services {
            get {
                return ResourceManager.GetString("Art_Advisory_Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        public static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buyer FAQ.
        /// </summary>
        public static string Buyer_FAQ {
            get {
                return ResourceManager.GetString("Buyer_FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Careers.
        /// </summary>
        public static string Careers {
            get {
                return ResourceManager.GetString("Careers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marked Prints.
        /// </summary>
        public static string Catalog {
            get {
                return ResourceManager.GetString("Catalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string Contact_Us {
            get {
                return ResourceManager.GetString("Contact_Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2017 R24. All rights reserved..
        /// </summary>
        public static string Copyright_msg {
            get {
                return ResourceManager.GetString("Copyright_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright Policy.
        /// </summary>
        public static string Copyright_Policy {
            get {
                return ResourceManager.GetString("Copyright_Policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curator’s Circle.
        /// </summary>
        public static string Curator_Circle {
            get {
                return ResourceManager.GetString("Curator_Circle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up for our newsletter.
        /// </summary>
        public static string Email_header1 {
            get {
                return ResourceManager.GetString("Email_header1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover new original artworks all around the world.
        /// </summary>
        public static string Email_header2 {
            get {
                return ResourceManager.GetString("Email_header2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Agencys.
        /// </summary>
        public static string For_Agencys {
            get {
                return ResourceManager.GetString("For_Agencys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Buyers.
        /// </summary>
        public static string For_Buyers {
            get {
                return ResourceManager.GetString("For_Buyers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R24 Logo.
        /// </summary>
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press.
        /// </summary>
        public static string Press {
            get {
                return ResourceManager.GetString("Press", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string Privacy_Policy {
            get {
                return ResourceManager.GetString("Privacy_Policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal.
        /// </summary>
        public static string R24 {
            get {
                return ResourceManager.GetString("R24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal Condition / .
        /// </summary>
        public static string R24_Art {
            get {
                return ResourceManager.GetString("R24_Art", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Service.
        /// </summary>
        public static string Terms_of_Service {
            get {
                return ResourceManager.GetString("Terms_of_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testimonials.
        /// </summary>
        public static string Testimonials {
            get {
                return ResourceManager.GetString("Testimonials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why Sell.
        /// </summary>
        public static string Why_Sell {
            get {
                return ResourceManager.GetString("Why_Sell", resourceCulture);
            }
        }
    }
}
