//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProfileRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProfileRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ProfileRes", typeof(ProfileRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Me.
        /// </summary>
        public static string About_me {
            get {
                return ResourceManager.GetString("About_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Information.
        /// </summary>
        public static string Account_info {
            get {
                return ResourceManager.GetString("Account_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Holder.
        /// </summary>
        public static string AccountHolder {
            get {
                return ResourceManager.GetString("AccountHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Number.
        /// </summary>
        public static string AccountNumber {
            get {
                return ResourceManager.GetString("AccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you have {0} in your account.
        /// </summary>
        public static string accountValue {
            get {
                return ResourceManager.GetString("accountValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address and Identification.
        /// </summary>
        public static string Address_Identification {
            get {
                return ResourceManager.GetString("Address_Identification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agency.
        /// </summary>
        public static string Agency {
            get {
                return ResourceManager.GetString("Agency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artwork.
        /// </summary>
        public static string Artwork {
            get {
                return ResourceManager.GetString("Artwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Profile.
        /// </summary>
        public static string Back_to_profile {
            get {
                return ResourceManager.GetString("Back_to_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Name.
        /// </summary>
        public static string BankName {
            get {
                return ResourceManager.GetString("BankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Number.
        /// </summary>
        public static string CardNumber {
            get {
                return ResourceManager.GetString("CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection Description.
        /// </summary>
        public static string Collection_description {
            get {
                return ResourceManager.GetString("Collection_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection Title.
        /// </summary>
        public static string Collection_title {
            get {
                return ResourceManager.GetString("Collection_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collections.
        /// </summary>
        public static string Collections {
            get {
                return ResourceManager.GetString("Collections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collector.
        /// </summary>
        public static string Collector {
            get {
                return ResourceManager.GetString("Collector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community.
        /// </summary>
        public static string Community {
            get {
                return ResourceManager.GetString("Community", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string Confirm_password {
            get {
                return ResourceManager.GetString("Confirm_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a New Collection.
        /// </summary>
        public static string Create_collection {
            get {
                return ResourceManager.GetString("Create_collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this collection? This cannot be undone..
        /// </summary>
        public static string DeleteCollection_msg {
            get {
                return ResourceManager.GetString("DeleteCollection_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        public static string Education {
            get {
                return ResourceManager.GetString("Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string Email_address {
            get {
                return ResourceManager.GetString("Email_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exhibitions.
        /// </summary>
        public static string Exhibitions {
            get {
                return ResourceManager.GetString("Exhibitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        public static string Facebook {
            get {
                return ResourceManager.GetString("Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        public static string Favorites {
            get {
                return ResourceManager.GetString("Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string First_Name {
            get {
                return ResourceManager.GetString("First_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Plus.
        /// </summary>
        public static string Google_plus {
            get {
                return ResourceManager.GetString("Google_plus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We checking ID for fraudulent, fake or defaced cards, so we must receive a copy of your government issued ID (for instance your passport or driver’s license) to be able to put your work for sale.
        ///Do not worry! We protect the file you have sent us. The file will be encrypted from the moment that you sent it. We keep your encrypted file on our servers and can only our administrative team can view it..
        /// </summary>
        public static string GovermentID_p1 {
            get {
                return ResourceManager.GetString("GovermentID_p1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For more information, please check our .
        /// </summary>
        public static string GovermentID_p2 {
            get {
                return ResourceManager.GetString("GovermentID_p2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If promoting your art under a pseudonym or nickname, you need to enter your LEGAL name below. We won&apos;t make this information public..
        /// </summary>
        public static string GovermentID_p3 {
            get {
                return ResourceManager.GetString("GovermentID_p3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string GovermentID_p3_continue {
            get {
                return ResourceManager.GetString("GovermentID_p3_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy..
        /// </summary>
        public static string GovermentID_privacyPolicy {
            get {
                return ResourceManager.GetString("GovermentID_privacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreement.
        /// </summary>
        public static string GovermentID_title {
            get {
                return ResourceManager.GetString("GovermentID_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your ID has been confirmed.
        /// </summary>
        public static string IDConfirmText {
            get {
                return ResourceManager.GetString("IDConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artwork Pick Up Address.
        /// </summary>
        public static string Identification_header {
            get {
                return ResourceManager.GetString("Identification_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Government Issued Identification.
        /// </summary>
        public static string Identification_header2 {
            get {
                return ResourceManager.GetString("Identification_header2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you add a new artwork, we will autofill your address with this information..
        /// </summary>
        public static string Identification_p {
            get {
                return ResourceManager.GetString("Identification_p", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to pay you for art sales we need a digital copy of your government issued identification. This will help us ensure that your commissions are paid out in a timely manner..
        /// </summary>
        public static string Identification_p2 {
            get {
                return ResourceManager.GetString("Identification_p2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instagram.
        /// </summary>
        public static string Instagram {
            get {
                return ResourceManager.GetString("Instagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string Last_name {
            get {
                return ResourceManager.GetString("Last_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailing List.
        /// </summary>
        public static string Mailing_list {
            get {
                return ResourceManager.GetString("Mailing_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Artworks.
        /// </summary>
        public static string Manage_artworks {
            get {
                return ResourceManager.GetString("Manage_artworks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Collections.
        /// </summary>
        public static string My_collections {
            get {
                return ResourceManager.GetString("My_collections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Website.
        /// </summary>
        public static string My_website {
            get {
                return ResourceManager.GetString("My_website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string New_password {
            get {
                return ResourceManager.GetString("New_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file chosen.
        /// </summary>
        public static string No_file_chosen {
            get {
                return ResourceManager.GetString("No_file_chosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not payed.
        /// </summary>
        public static string Notpayed {
            get {
                return ResourceManager.GetString("Notpayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password should be more than 6 characters..
        /// </summary>
        public static string Password_desc_1 {
            get {
                return ResourceManager.GetString("Password_desc_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a combination of characters, numbers and punctuations..
        /// </summary>
        public static string Password_desc_2 {
            get {
                return ResourceManager.GetString("Password_desc_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords are case sensitive..
        /// </summary>
        public static string Password_desc_3 {
            get {
                return ResourceManager.GetString("Password_desc_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payed.
        /// </summary>
        public static string Payed {
            get {
                return ResourceManager.GetString("Payed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a pending payout request. Please complete the prior request before applying a new one..
        /// </summary>
        public static string Payout_Error {
            get {
                return ResourceManager.GetString("Payout_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payouts.
        /// </summary>
        public static string Payouts {
            get {
                return ResourceManager.GetString("Payouts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pending.
        /// </summary>
        public static string pending {
            get {
                return ResourceManager.GetString("pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhoneNumber.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pinterest.
        /// </summary>
        public static string Pinterest {
            get {
                return ResourceManager.GetString("Pinterest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portfolio.
        /// </summary>
        public static string Portfolio {
            get {
                return ResourceManager.GetString("Portfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        public static string Private {
            get {
                return ResourceManager.GetString("Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Address.
        /// </summary>
        public static string Profile_address {
            get {
                return ResourceManager.GetString("Profile_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Image.
        /// </summary>
        public static string Profile_image {
            get {
                return ResourceManager.GetString("Profile_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile information.
        /// </summary>
        public static string Profile_information {
            get {
                return ResourceManager.GetString("Profile_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Type.
        /// </summary>
        public static string Profile_type {
            get {
                return ResourceManager.GetString("Profile_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        public static string ProfileInfo_header {
            get {
                return ResourceManager.GetString("ProfileInfo_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Information.
        /// </summary>
        public static string ProfileInfo_header2 {
            get {
                return ResourceManager.GetString("ProfileInfo_header2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;ll add icons with links to any of the below sites that you provide..
        /// </summary>
        public static string ProfileInfo_p1 {
            get {
                return ResourceManager.GetString("ProfileInfo_p1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share with collectors here about who you are, where you&apos;ve studied, and any upcoming or past events and exhibitions..
        /// </summary>
        public static string ProfileInfo_p2 {
            get {
                return ResourceManager.GetString("ProfileInfo_p2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive Art Uploaded Email.
        /// </summary>
        public static string Receive_Art_Uploaded_Email {
            get {
                return ResourceManager.GetString("Receive_Art_Uploaded_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Payout.
        /// </summary>
        public static string Requestpayout {
            get {
                return ResourceManager.GetString("Requestpayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales.
        /// </summary>
        public static string Sales {
            get {
                return ResourceManager.GetString("Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Dashboard.
        /// </summary>
        public static string Sales_Dashboard {
            get {
                return ResourceManager.GetString("Sales_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string Save_changes {
            get {
                return ResourceManager.GetString("Save_changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select File.
        /// </summary>
        public static string Select_file {
            get {
                return ResourceManager.GetString("Select_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Form.
        /// </summary>
        public static string Tax_form {
            get {
                return ResourceManager.GetString("Tax_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Price.
        /// </summary>
        public static string TotalPrice {
            get {
                return ResourceManager.GetString("TotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tumblr.
        /// </summary>
        public static string Tumblr {
            get {
                return ResourceManager.GetString("Tumblr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter.
        /// </summary>
        public static string Twitter {
            get {
                return ResourceManager.GetString("Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price.
        /// </summary>
        public static string UnitPrice {
            get {
                return ResourceManager.GetString("UnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Art.
        /// </summary>
        public static string Upload_art {
            get {
                return ResourceManager.GetString("Upload_art", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload ID.
        /// </summary>
        public static string Upload_id {
            get {
                return ResourceManager.GetString("Upload_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Profile Image.
        /// </summary>
        public static string Upload_photo_header {
            get {
                return ResourceManager.GetString("Upload_photo_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an image to upload..
        /// </summary>
        public static string Upload_photo_p {
            get {
                return ResourceManager.GetString("Upload_photo_p", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZipCode.
        /// </summary>
        public static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
    }
}
