//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SearchRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SearchRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SearchRes", typeof(SearchRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a Frame.
        /// </summary>
        public static string Add_frame {
            get {
                return ResourceManager.GetString("Add_frame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Cart.
        /// </summary>
        public static string Add_to_Cart {
            get {
                return ResourceManager.GetString("Add_to_Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Categories.
        /// </summary>
        public static string All_Categories {
            get {
                return ResourceManager.GetString("All_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Media.
        /// </summary>
        public static string All_Mediums {
            get {
                return ResourceManager.GetString("All_Mediums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Prices.
        /// </summary>
        public static string All_Prices {
            get {
                return ResourceManager.GetString("All_Prices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Styles.
        /// </summary>
        public static string All_Styles {
            get {
                return ResourceManager.GetString("All_Styles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Subjects.
        /// </summary>
        public static string All_Subjects {
            get {
                return ResourceManager.GetString("All_Subjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        public static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Art Description.
        /// </summary>
        public static string Art_description {
            get {
                return ResourceManager.GetString("Art_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Art Selected by our Curators.
        /// </summary>
        public static string Art_Selected_by_our_Curators {
            get {
                return ResourceManager.GetString("Art_Selected_by_our_Curators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse Art for Sale by Category.
        /// </summary>
        public static string Browse_Art_for_Sale_by_Category {
            get {
                return ResourceManager.GetString("Browse_Art_for_Sale_by_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse Art for Sale by Style.
        /// </summary>
        public static string Browse_Art_for_Sale_by_Style {
            get {
                return ResourceManager.GetString("Browse_Art_for_Sale_by_Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse Art for Sale by Price.
        /// </summary>
        public static string Browse_Art_for_Sale_Price {
            get {
                return ResourceManager.GetString("Browse_Art_for_Sale_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by.
        /// </summary>
        public static string by {
            get {
                return ResourceManager.GetString("by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose from List.
        /// </summary>
        public static string Choose_from_list {
            get {
                return ResourceManager.GetString("Choose_from_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,.
        /// </summary>
        public static string Comma {
            get {
                return ResourceManager.GetString("Comma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover new original artwork from around the world.
        /// </summary>
        public static string discover_new_original {
            get {
                return ResourceManager.GetString("discover_new_original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords.
        /// </summary>
        public static string Keywords {
            get {
                return ResourceManager.GetString("Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7-day money back guarantee.
        /// </summary>
        public static string Money_back {
            get {
                return ResourceManager.GetString("Money_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on.
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orginal.
        /// </summary>
        public static string Orginal {
            get {
                return ResourceManager.GetString("Orginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prints.
        /// </summary>
        public static string Prints {
            get {
                return ResourceManager.GetString("Prints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Edition Prints Available:.
        /// </summary>
        public static string Product_print_header {
            get {
                return ResourceManager.GetString("Product_print_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no result with your parameters.
        /// </summary>
        public static string resultEmpty {
            get {
                return ResourceManager.GetString("resultEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Material.
        /// </summary>
        public static string Select_material {
            get {
                return ResourceManager.GetString("Select_material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Size.
        /// </summary>
        public static string Select_size {
            get {
                return ResourceManager.GetString("Select_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping cost by customer.
        /// </summary>
        public static string Shipping_included {
            get {
                return ResourceManager.GetString("Shipping_included", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ships in a.
        /// </summary>
        public static string Ships_in {
            get {
                return ResourceManager.GetString("Ships_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Artworks.
        /// </summary>
        public static string ViewArtwork {
            get {
                return ResourceManager.GetString("ViewArtwork", resourceCulture);
            }
        }
    }
}
