//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ShareRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShareRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ShareRes", typeof(ShareRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account successfuly activated.
        /// </summary>
        public static string Account_confirmed {
            get {
                return ResourceManager.GetString("Account_confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Information.
        /// </summary>
        public static string AccountInformation {
            get {
                return ResourceManager.GetString("AccountInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to a Collection.
        /// </summary>
        public static string Add_to_a_Collection {
            get {
                return ResourceManager.GetString("Add_to_a_Collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Cart.
        /// </summary>
        public static string Add_to_cart {
            get {
                return ResourceManager.GetString("Add_to_cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Favorites.
        /// </summary>
        public static string Add_to_Favorites {
            get {
                return ResourceManager.GetString("Add_to_Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agency.
        /// </summary>
        public static string Agency {
            get {
                return ResourceManager.GetString("Agency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        public static string Already_have {
            get {
                return ResourceManager.GetString("Already_have", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        public static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive.
        /// </summary>
        public static string archive {
            get {
                return ResourceManager.GetString("archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you a buyer?.
        /// </summary>
        public static string Are_You_Buyer {
            get {
                return ResourceManager.GetString("Are_You_Buyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Art.
        /// </summary>
        public static string Art {
            get {
                return ResourceManager.GetString("Art", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Art Print.
        /// </summary>
        public static string Art_print {
            get {
                return ResourceManager.GetString("Art_print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artworks.
        /// </summary>
        public static string Artworks {
            get {
                return ResourceManager.GetString("Artworks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artworks from.
        /// </summary>
        public static string Artworks_from {
            get {
                return ResourceManager.GetString("Artworks_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artworks up to.
        /// </summary>
        public static string Artworks_up_to {
            get {
                return ResourceManager.GetString("Artworks_up_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bid.
        /// </summary>
        public static string Bid {
            get {
                return ResourceManager.GetString("Bid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bids.
        /// </summary>
        public static string Bids {
            get {
                return ResourceManager.GetString("Bids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        public static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box.
        /// </summary>
        public static string Box {
            get {
                return ResourceManager.GetString("Box", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here.
        /// </summary>
        public static string Click_here {
            get {
                return ResourceManager.GetString("Click_here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection.
        /// </summary>
        public static string Collection {
            get {
                return ResourceManager.GetString("Collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cant Add to your Collection.
        /// </summary>
        public static string collectionAddFaild {
            get {
                return ResourceManager.GetString("collectionAddFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Added to your Collection.
        /// </summary>
        public static string collectionAddSuccess {
            get {
                return ResourceManager.GetString("collectionAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collections.
        /// </summary>
        public static string Collections {
            get {
                return ResourceManager.GetString("Collections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am a collector.
        /// </summary>
        public static string Collector {
            get {
                return ResourceManager.GetString("Collector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        public static string Contactus {
            get {
                return ResourceManager.GetString("Contactus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright Policy.
        /// </summary>
        public static string Copyright_policy {
            get {
                return ResourceManager.GetString("Copyright_policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crate.
        /// </summary>
        public static string Crate {
            get {
                return ResourceManager.GetString("Crate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        public static string Created_in {
            get {
                return ResourceManager.GetString("Created_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Price.
        /// </summary>
        public static string Current_Price {
            get {
                return ResourceManager.GetString("Current_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for giving R24 the opportunity to serve you..
        /// </summary>
        public static string Email_p1 {
            get {
                return ResourceManager.GetString("Email_p1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here is a list of the artwork(s) you purchased and details about your payment..
        /// </summary>
        public static string Email_p2 {
            get {
                return ResourceManager.GetString("Email_p2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have any question or require clarification please email to Support@cuber.dev. We look forward to serving you in the future..
        /// </summary>
        public static string Email_p3 {
            get {
                return ResourceManager.GetString("Email_p3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regards.
        /// </summary>
        public static string Email_p4 {
            get {
                return ResourceManager.GetString("Email_p4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R24 Team.
        /// </summary>
        public static string Email_p5 {
            get {
                return ResourceManager.GetString("Email_p5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        public static string Email_p6 {
            get {
                return ResourceManager.GetString("Email_p6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How do I cancel my account? ,
        ///How do I price my artwork? ,
        ///How do I request a payout? ,
        ///How do I upload and edit an image? ,
        ///I am experiencing technical issues ,
        ///I am having issues uploading an image ,
        ///I have a question on the tax form ,
        ///Who pays for shipping costs? ,
        ///Why is my artwork not for sale? ,
        ///How do I get started to sell my artwork? ,
        ///Where is my payout? ,
        ///Other Question.
        /// </summary>
        public static string FAQ_Agency_questions {
            get {
                return ResourceManager.GetString("FAQ_Agency_questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agency Name.
        /// </summary>
        public static string FAQ_AgencyName {
            get {
                return ResourceManager.GetString("FAQ_AgencyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artwork Title.
        /// </summary>
        public static string FAQ_ArtworkTitle {
            get {
                return ResourceManager.GetString("FAQ_ArtworkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments.
        /// </summary>
        public static string FAQ_Attachment {
            get {
                return ResourceManager.GetString("FAQ_Attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please verify that you are human.
        /// </summary>
        public static string FAQ_Captcha {
            get {
                return ResourceManager.GetString("FAQ_Captcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistance placing an order ,
        ///Question about my recent purchase ,
        ///Returns and refund policy ,
        ///How do I cancel an order? ,
        ///How can I work with a curator? ,
        ///I am having Technical issues and need assistance ,
        ///Can R24 appraise and/or sell artwork I own? ,
        ///Other.
        /// </summary>
        public static string FAQ_Collector_questions {
            get {
                return ResourceManager.GetString("FAQ_Collector_questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide details of your request below..
        /// </summary>
        public static string FAQ_description {
            get {
                return ResourceManager.GetString("FAQ_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email address.
        /// </summary>
        public static string FAQ_email {
            get {
                return ResourceManager.GetString("FAQ_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Name.
        /// </summary>
        public static string FAQ_Name {
            get {
                return ResourceManager.GetString("FAQ_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string FAQ_PhoneNumber {
            get {
                return ResourceManager.GetString("FAQ_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select your question.
        /// </summary>
        public static string FAQ_question {
            get {
                return ResourceManager.GetString("FAQ_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string FAQ_subject {
            get {
                return ResourceManager.GetString("FAQ_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string FAQ_Submit {
            get {
                return ResourceManager.GetString("FAQ_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUBMIT A REQUEST.
        /// </summary>
        public static string FAQ_Title {
            get {
                return ResourceManager.GetString("FAQ_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a request type below.
        /// </summary>
        public static string FAQ_Type {
            get {
                return ResourceManager.GetString("FAQ_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am an Agency and have a question.
        /// </summary>
        public static string FAQ_Type_0 {
            get {
                return ResourceManager.GetString("FAQ_Type_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am a Collector and have a question.
        /// </summary>
        public static string FAQ_Type_1 {
            get {
                return ResourceManager.GetString("FAQ_Type_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact The Agency.
        /// </summary>
        public static string FAQ_Type_2 {
            get {
                return ResourceManager.GetString("FAQ_Type_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commission Request.
        /// </summary>
        public static string FAQ_Type_3 {
            get {
                return ResourceManager.GetString("FAQ_Type_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile URL.
        /// </summary>
        public static string FAQ_URL {
            get {
                return ResourceManager.GetString("FAQ_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Removed from your favorites.
        /// </summary>
        public static string FavAddFail {
            get {
                return ResourceManager.GetString("FavAddFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Added to your favorites.
        /// </summary>
        public static string FavAddSuccess {
            get {
                return ResourceManager.GetString("FavAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        public static string Favorites {
            get {
                return ResourceManager.GetString("Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured.
        /// </summary>
        public static string Featured {
            get {
                return ResourceManager.GetString("Featured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string Forgot_password {
            get {
                return ResourceManager.GetString("Forgot_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have a Question? Ask or enter a search term here..
        /// </summary>
        public static string Have_Question {
            get {
                return ResourceManager.GetString("Have_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am an Agency.
        /// </summary>
        public static string I_Agency {
            get {
                return ResourceManager.GetString("I_Agency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load more.
        /// </summary>
        public static string Load_more {
            get {
                return ResourceManager.GetString("Load_more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R24 Logo.
        /// </summary>
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New to R24.
        /// </summary>
        public static string New_R24 {
            get {
                return ResourceManager.GetString("New_R24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string of {
            get {
                return ResourceManager.GetString("of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Date.
        /// </summary>
        public static string Order_date {
            get {
                return ResourceManager.GetString("Order_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        public static string OrderStatus_Canceled {
            get {
                return ResourceManager.GetString("OrderStatus_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delivered.
        /// </summary>
        public static string OrderStatus_Delivered {
            get {
                return ResourceManager.GetString("OrderStatus_Delivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pending.
        /// </summary>
        public static string OrderStatus_NoSeen {
            get {
                return ResourceManager.GetString("OrderStatus_NoSeen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to posted.
        /// </summary>
        public static string OrderStatus_Posted {
            get {
                return ResourceManager.GetString("OrderStatus_Posted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seen.
        /// </summary>
        public static string OrderStatus_Seen {
            get {
                return ResourceManager.GetString("OrderStatus_Seen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posted by.
        /// </summary>
        public static string Posted_by {
            get {
                return ResourceManager.GetString("Posted_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string Privacy_policy {
            get {
                return ResourceManager.GetString("Privacy_policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        public static string Qty {
            get {
                return ResourceManager.GetString("Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt.
        /// </summary>
        public static string Receipt {
            get {
                return ResourceManager.GetString("Receipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank You! Please check your email to activate your account..
        /// </summary>
        public static string Register_confirmationSent {
            get {
                return ResourceManager.GetString("Register_confirmationSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By signing up, you agree to our.
        /// </summary>
        public static string Register_des_p1 {
            get {
                return ResourceManager.GetString("Register_des_p1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ll receive weekly updates on recently added artworks, new curated collections, featured Agencys, and more..
        /// </summary>
        public static string Register_des_p2 {
            get {
                return ResourceManager.GetString("Register_des_p2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You’ll be able to change this later.
        /// </summary>
        public static string Register_header2 {
            get {
                return ResourceManager.GetString("Register_header2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RELATED ARTICLES.
        /// </summary>
        public static string Related_articles {
            get {
                return ResourceManager.GetString("Related_articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Favorite.
        /// </summary>
        public static string Remove_from_favorites {
            get {
                return ResourceManager.GetString("Remove_from_favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to results for.
        /// </summary>
        public static string Results_for {
            get {
                return ResourceManager.GetString("Results_for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to Art Details.
        /// </summary>
        public static string Return_to_Art_Details {
            get {
                return ResourceManager.GetString("Return_to_Art_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Dashboard.
        /// </summary>
        public static string SalesDashboard {
            get {
                return ResourceManager.GetString("SalesDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search results.
        /// </summary>
        public static string Search_results {
            get {
                return ResourceManager.GetString("Search_results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your profile type.
        /// </summary>
        public static string Select_profile_type {
            get {
                return ResourceManager.GetString("Select_profile_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping price.
        /// </summary>
        public static string Shipping_price {
            get {
                return ResourceManager.GetString("Shipping_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ships in a.
        /// </summary>
        public static string Ships_in {
            get {
                return ResourceManager.GetString("Ships_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing.
        /// </summary>
        public static string Showing {
            get {
                return ResourceManager.GetString("Showing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Price.
        /// </summary>
        public static string Starting_price {
            get {
                return ResourceManager.GetString("Starting_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style.
        /// </summary>
        public static string Style {
            get {
                return ResourceManager.GetString("Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit a request.
        /// </summary>
        public static string Submit_request {
            get {
                return ResourceManager.GetString("Submit_request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitted On.
        /// </summary>
        public static string Submitted_on {
            get {
                return ResourceManager.GetString("Submitted_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success_message {
            get {
                return ResourceManager.GetString("Success_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tagged.
        /// </summary>
        public static string Tagged {
            get {
                return ResourceManager.GetString("Tagged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms.
        /// </summary>
        public static string Terms {
            get {
                return ResourceManager.GetString("Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Use.
        /// </summary>
        public static string Terms_use {
            get {
                return ResourceManager.GetString("Terms_use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to view Buyer FAQs.
        /// </summary>
        public static string To_view_Buyer_FAQs {
            get {
                return ResourceManager.GetString("To_view_Buyer_FAQs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total amount paid.
        /// </summary>
        public static string Total_amount_paid {
            get {
                return ResourceManager.GetString("Total_amount_paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tube.
        /// </summary>
        public static string Tube {
            get {
                return ResourceManager.GetString("Tube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit price.
        /// </summary>
        public static string Unit_price {
            get {
                return ResourceManager.GetString("Unit_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Fullscreen.
        /// </summary>
        public static string View_Fullscreen {
            get {
                return ResourceManager.GetString("View_Fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View in a Room.
        /// </summary>
        public static string View_in_a_Room {
            get {
                return ResourceManager.GetString("View_in_a_Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View More.
        /// </summary>
        public static string View_more {
            get {
                return ResourceManager.GetString("View_more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your decision to visit! We will assist you in scheduling a visit.
        ///Requests are processed Saturday through Wednesday from 9:30am-5:30pm.  If submitted after these posted times, your request will be processed on the next business day.  Once received, a representative will contact you within 2 business days to confirm the details of your visit. 
        ///
        ///For questions or additional information, please feel free to contact us at (+98) 222-2222 or email info@cuber.dev.
        /// </summary>
        public static string Visit_description {
            get {
                return ResourceManager.GetString("Visit_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit request.
        /// </summary>
        public static string Visit_request {
            get {
                return ResourceManager.GetString("Visit_request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome back!.
        /// </summary>
        public static string Welcome_back {
            get {
                return ResourceManager.GetString("Welcome_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With specification.
        /// </summary>
        public static string With_specification {
            get {
                return ResourceManager.GetString("With_specification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not any collection.
        /// </summary>
        public static string You_have_not_any_collection {
            get {
                return ResourceManager.GetString("You_have_not_any_collection", resourceCulture);
            }
        }
    }
}
