//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UploadRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UploadRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.UploadRes", typeof(UploadRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 2.
        /// </summary>
        public static string Address_2 {
            get {
                return ResourceManager.GetString("Address_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agency can not be left blank.
        /// </summary>
        public static string AgencyName_Null_error {
            get {
                return ResourceManager.GetString("AgencyName_Null_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artwork Image.
        /// </summary>
        public static string Artwork_Image {
            get {
                return ResourceManager.GetString("Artwork_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artwork Status.
        /// </summary>
        public static string Artwork_Status {
            get {
                return ResourceManager.GetString("Artwork_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artwork Details.
        /// </summary>
        public static string ArtworkDetail {
            get {
                return ResourceManager.GetString("ArtworkDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limited Edition is wrong ????.
        /// </summary>
        public static string avaibleEntity_error {
            get {
                return ResourceManager.GetString("avaibleEntity_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box.
        /// </summary>
        public static string Box {
            get {
                return ResourceManager.GetString("Box", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be the copyright owner to post an artwork.
        /// </summary>
        public static string copyright_error {
            get {
                return ResourceManager.GetString("copyright_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crate.
        /// </summary>
        public static string Crate {
            get {
                return ResourceManager.GetString("Crate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth.
        /// </summary>
        public static string Depth {
            get {
                return ResourceManager.GetString("Depth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description should be at least 10 characters long..
        /// </summary>
        public static string descriptionnull_error {
            get {
                return ResourceManager.GetString("descriptionnull_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  value can not be left blank.
        /// </summary>
        public static string Empty_Error {
            get {
                return ResourceManager.GetString("Empty_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Sale.
        /// </summary>
        public static string foresale {
            get {
                return ResourceManager.GetString("foresale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the specifications of the artwork frame.
        /// </summary>
        public static string Frame_description {
            get {
                return ResourceManager.GetString("Frame_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image cannot be empty.
        /// </summary>
        public static string Image_cannot_be_empty {
            get {
                return ResourceManager.GetString("Image_cannot_be_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to centimeter.
        /// </summary>
        public static string inches {
            get {
                return ResourceManager.GetString("inches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter 5-12 Keywords.
        /// </summary>
        public static string keyword_lenght_error {
            get {
                return ResourceManager.GetString("keyword_lenght_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limited Edition.
        /// </summary>
        public static string Limited_Edition {
            get {
                return ResourceManager.GetString("Limited_Edition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not for sale.
        /// </summary>
        public static string notforsale {
            get {
                return ResourceManager.GetString("notforsale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string of {
            get {
                return ResourceManager.GetString("of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packaging.
        /// </summary>
        public static string Packaging {
            get {
                return ResourceManager.GetString("Packaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photography.
        /// </summary>
        public static string Photography {
            get {
                return ResourceManager.GetString("Photography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kilograms.
        /// </summary>
        public static string pounds {
            get {
                return ResourceManager.GetString("pounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pricing.
        /// </summary>
        public static string Pricing {
            get {
                return ResourceManager.GetString("Pricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Agency.
        /// </summary>
        public static string Select_Agency {
            get {
                return ResourceManager.GetString("Select_Agency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a category to help collectors to find your work easily.
        /// </summary>
        public static string select_category_str {
            get {
                return ResourceManager.GetString("select_category_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select subject /category.
        /// </summary>
        public static string select_subject {
            get {
                return ResourceManager.GetString("select_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Image.
        /// </summary>
        public static string SelectImage {
            get {
                return ResourceManager.GetString("SelectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sold.
        /// </summary>
        public static string sold {
            get {
                return ResourceManager.GetString("sold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category &amp; Subject.
        /// </summary>
        public static string step1_next_click {
            get {
                return ResourceManager.GetString("step1_next_click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price your artwork and see the all-in price collectors will see..
        /// </summary>
        public static string step10_description {
            get {
                return ResourceManager.GetString("step10_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price of artwork.
        /// </summary>
        public static string step10_l1 {
            get {
                return ResourceManager.GetString("step10_l1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Profit (90%).
        /// </summary>
        public static string step10_l2 {
            get {
                return ResourceManager.GetString("step10_l2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping &amp; handling paid by collector.
        /// </summary>
        public static string step10_l3 {
            get {
                return ResourceManager.GetString("step10_l3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price that seller will see.
        /// </summary>
        public static string step10_l4 {
            get {
                return ResourceManager.GetString("step10_l4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string step10_next_click {
            get {
                return ResourceManager.GetString("step10_next_click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping.
        /// </summary>
        public static string step10_pre_click {
            get {
                return ResourceManager.GetString("step10_pre_click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artwork Status.
        /// </summary>
        public static string step2_next_click {
            get {
                return ResourceManager.GetString("step2_next_click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string step2_pre_click {
            get {
                return ResourceManager.GetString("step2_pre_click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you the copyright owner of this artwork?.
        /// </summary>
        public static string step3_copyright_string {
            get {
                return ResourceManager.GetString("step3_copyright_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let us know how you&apos;d like to sell your artwork.
        /// </summary>
        public static string step3_detail {
            get {
                return ResourceManager.GetString("step3_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the original artwork for sale?.
        /// </summary>
        public static string step3_forsale_string {
            get {
                return ResourceManager.GetString("step3_forsale_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artwork Image.
        /// </summary>
        public static string step3_next_click {
            get {
                return ResourceManager.GetString("step3_next_click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category  &amp; Subject.
        /// </summary>
        public static string step3_pre_click {
            get {
                return ResourceManager.GetString("step3_pre_click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to make it available for prints?.
        /// </summary>
        public static string step3_print_avaible_string {
            get {
                return ResourceManager.GetString("step3_print_avaible_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which year did you create this artwork?.
        /// </summary>
        public static string step3_year_string {
            get {
                return ResourceManager.GetString("step3_year_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify your image to adjust your artwork to display across the site..
        /// </summary>
        public static string step4_detail {
            get {
                return ResourceManager.GetString("step4_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mediums, Materials, &amp; Styles.
        /// </summary>
        public static string step4_next_click {
            get {
                return ResourceManager.GetString("step4_next_click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artwork Status.
        /// </summary>
        public static string step4_pre_click {
            get {
                return ResourceManager.GetString("step4_pre_click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell us more about your artwork.
        /// </summary>
        public static string step5_description {
            get {
                return ResourceManager.GetString("step5_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords.
        /// </summary>
        public static string step5_keywords {
            get {
                return ResourceManager.GetString("step5_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By tagging your artwork and using keywords, you raise the chance of your work being noticed. The best keywords are the ones which are simple, regularly used in search and describing the visual elements of your work such as subject, style, materials, and color. We recommend to use the strongest keywords first. For more information please see.
        /// </summary>
        public static string step5_keywords_detail {
            get {
                return ResourceManager.GetString("step5_keywords_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here.
        /// </summary>
        public static string step5_keywords_detail_here {
            get {
                return ResourceManager.GetString("step5_keywords_detail_here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string step5_keywords_detail_here_continue {
            get {
                return ResourceManager.GetString("step5_keywords_detail_here_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter 5-12 Keywords.
        /// </summary>
        public static string step5_keywords_lable {
            get {
                return ResourceManager.GetString("step5_keywords_lable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select 1-5 Materials.
        /// </summary>
        public static string step5_materials {
            get {
                return ResourceManager.GetString("step5_materials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select 1-5 Mediums.
        /// </summary>
        public static string step5_mediums {
            get {
                return ResourceManager.GetString("step5_mediums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimensions.
        /// </summary>
        public static string step5_next_click {
            get {
                return ResourceManager.GetString("step5_next_click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artwork Image.
        /// </summary>
        public static string step5_pre_click {
            get {
                return ResourceManager.GetString("step5_pre_click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select 1-5 Styles.
        /// </summary>
        public static string step5_styles {
            get {
                return ResourceManager.GetString("step5_styles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mediums, Materials, Styles.
        /// </summary>
        public static string step5_title {
            get {
                return ResourceManager.GetString("step5_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It’s very important that you provide accurate dimensions as collectors and trade clients need to know the exact size of an artwork before purchasing it. For flat artworks, such as photographs and other works on paper, we suggest that you enter a depth of 0.1..
        /// </summary>
        public static string step6_description {
            get {
                return ResourceManager.GetString("step6_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string step6_next_click {
            get {
                return ResourceManager.GetString("step6_next_click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media, Materials, Styles.
        /// </summary>
        public static string step6_pre_click {
            get {
                return ResourceManager.GetString("step6_pre_click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimensions.
        /// </summary>
        public static string step6_title {
            get {
                return ResourceManager.GetString("step6_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agency.
        /// </summary>
        public static string step7_Agency {
            get {
                return ResourceManager.GetString("step7_Agency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you do not find Agency name in the list of Agencys, please contact us via email in order to add it to the list..
        /// </summary>
        public static string step7_Agency_description {
            get {
                return ResourceManager.GetString("step7_Agency_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What/who inspired the work?.
        /// </summary>
        public static string step7_ask_1 {
            get {
                return ResourceManager.GetString("step7_ask_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do you hope its viewers will feel?.
        /// </summary>
        public static string step7_ask_2 {
            get {
                return ResourceManager.GetString("step7_ask_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to why did you choose the medium,subject matter and style?.
        /// </summary>
        public static string step7_ask_3 {
            get {
                return ResourceManager.GetString("step7_ask_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collectors tend to appreciate works more if they know the “story” behind them, so we recommend that write informative artwork descriptions. Great descriptions not only provide useful information (e.g. physical texture, whether hanging hardware is included, quality of materials), but they also answer questions like:.
        /// </summary>
        public static string step7_description {
            get {
                return ResourceManager.GetString("step7_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packaging.
        /// </summary>
        public static string step7_next_click {
            get {
                return ResourceManager.GetString("step7_next_click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimensions.
        /// </summary>
        public static string step7_pre_click {
            get {
                return ResourceManager.GetString("step7_pre_click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string step7_title {
            get {
                return ResourceManager.GetString("step7_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 35 character limit.
        /// </summary>
        public static string step7_title_desc {
            get {
                return ResourceManager.GetString("step7_title_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the artwork framed?.
        /// </summary>
        public static string step8_ask1 {
            get {
                return ResourceManager.GetString("step8_ask1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the artwork multi-paneled?.
        /// </summary>
        public static string step8_ask2 {
            get {
                return ResourceManager.GetString("step8_ask2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell us how you&apos;d like to package your artwork.
        /// </summary>
        public static string step8_description {
            get {
                return ResourceManager.GetString("step8_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping.
        /// </summary>
        public static string step8_next_click {
            get {
                return ResourceManager.GetString("step8_next_click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string step8_pre_click {
            get {
                return ResourceManager.GetString("step8_pre_click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the shipping weight of your artwork.
        /// </summary>
        public static string step9_description {
            get {
                return ResourceManager.GetString("step9_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell us where your artwork will be picked up.
        /// </summary>
        public static string step9_description2 {
            get {
                return ResourceManager.GetString("step9_description2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pricing.
        /// </summary>
        public static string step9_next_click {
            get {
                return ResourceManager.GetString("step9_next_click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packaging.
        /// </summary>
        public static string step9_pre_click {
            get {
                return ResourceManager.GetString("step9_pre_click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Address.
        /// </summary>
        public static string step9_tilte2 {
            get {
                return ResourceManager.GetString("step9_tilte2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping.
        /// </summary>
        public static string step9_title {
            get {
                return ResourceManager.GetString("step9_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Address.
        /// </summary>
        public static string Street_Address {
            get {
                return ResourceManager.GetString("Street_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title cannot be longer than 35 characters.
        /// </summary>
        public static string TitleLenth_error {
            get {
                return ResourceManager.GetString("TitleLenth_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title can not be left blank.
        /// </summary>
        public static string titleNull_error {
            get {
                return ResourceManager.GetString("titleNull_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  tube.
        /// </summary>
        public static string Tube {
            get {
                return ResourceManager.GetString("Tube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload an image file should be at least 1200 x 1500 pixels and less than 50MB..
        /// </summary>
        public static string upload_string {
            get {
                return ResourceManager.GetString("upload_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upload successful.
        /// </summary>
        public static string upload_success {
            get {
                return ResourceManager.GetString("upload_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write here ....
        /// </summary>
        public static string Writehere {
            get {
                return ResourceManager.GetString("Writehere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth can not be zero.
        /// </summary>
        public static string zeroDepth_error {
            get {
                return ResourceManager.GetString("zeroDepth_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height can not be zero.
        /// </summary>
        public static string zeroHeight_error {
            get {
                return ResourceManager.GetString("zeroHeight_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width can not be zero.
        /// </summary>
        public static string zeroWidth_error {
            get {
                return ResourceManager.GetString("zeroWidth_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip/Postal Code.
        /// </summary>
        public static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
    }
}
